### PR TITLE
New empty

### PR DESCRIPTION
**Pull request by leerho**

### CODE REVIEW

**Comment by leerho** [comment]
This pull request **introduces 12 alerts** and **fixes 1** when merging 7796a01e0ad5bd0b635937c4b5dfaae683f5b0c9 into 90442a150daa219a34e02f12a9eee592320abef4 - [view on LGTM.com](https://lgtm.com/projects/g/DataSketches/sketches-core/rev/pr-f82e8a8a7d565554acb9fe8ff102f3cad0b0aa9d)

**new alerts:**

* 12 for Dereferenced variable may be null

**fixed alerts:**

* 1 for Dereferenced variable may be null

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by leerho** [comment]
This pull request **introduces 12 alerts** and **fixes 1** when merging d327234ab665606c9ce2aef8ab745af658d133fc into 90442a150daa219a34e02f12a9eee592320abef4 - [view on LGTM.com](https://lgtm.com/projects/g/DataSketches/sketches-core/rev/pr-efed118e7dd417dd9977e227cc901fc02be7c217)

**new alerts:**

* 12 for Dereferenced variable may be null

**fixed alerts:**

* 1 for Dereferenced variable may be null

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by AlexanderSaydakov** [comment]
looks good to me

**Comment by leerho** [comment]
This pull request **introduces 6 alerts** and **fixes 1** when merging 76483669065c89e8524bc756468c7f738fee31ab into 90442a150daa219a34e02f12a9eee592320abef4 - [view on LGTM.com](https://lgtm.com/projects/g/DataSketches/sketches-core/rev/pr-4ca51bfaa8035a3046ecc71e459f986d23cde5ed)

**new alerts:**

* 6 for Dereferenced variable may be null

**fixed alerts:**

* 1 for Dereferenced variable may be null

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by leerho** [comment]
This pull request **introduces 6 alerts** and **fixes 1** when merging 68dadd52c3bbc9f8202d5c3cfe67ba9e4eef7b25 into bd02cc3aa537f7666cbee5ac3d70e0147ead07b2 - [view on LGTM.com](https://lgtm.com/projects/g/DataSketches/sketches-core/rev/pr-7c90eddcf440a80ccda6401af6e5f75c38a19092)

**new alerts:**

* 6 for Dereferenced variable may be null

**fixed alerts:**

* 1 for Dereferenced variable may be null

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by leerho** [comment]
This pull request **introduces 6 alerts** and **fixes 1** when merging efd59a262e01a6a70324333460b0b9b63acf686a into bd02cc3aa537f7666cbee5ac3d70e0147ead07b2 - [view on LGTM.com](https://lgtm.com/projects/g/DataSketches/sketches-core/rev/pr-9ecff94c31ab69718c69b59e12c5f59dd1efc1dd)

**new alerts:**

* 6 for Dereferenced variable may be null

**fixed alerts:**

* 1 for Dereferenced variable may be null

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by leerho** [comment]
This pull request **introduces 6 alerts** and **fixes 1** when merging 4a973a7518844f08f5a0a0a864cfb48f548f0241 into bd02cc3aa537f7666cbee5ac3d70e0147ead07b2 - [view on LGTM.com](https://lgtm.com/projects/g/DataSketches/sketches-core/rev/pr-1ee20a29aafb95112ebc797ebbb214ffb0974542)

**new alerts:**

* 6 for Dereferenced variable may be null

**fixed alerts:**

* 1 for Dereferenced variable may be null

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by leerho** [comment]
This pull request **introduces 6 alerts** and **fixes 1** when merging f0477af1db1bd4b8ea7f389ee1c43b87d7500b8d into bd02cc3aa537f7666cbee5ac3d70e0147ead07b2 - [view on LGTM.com](https://lgtm.com/projects/g/DataSketches/sketches-core/rev/pr-46057c3afd766cc459edf8f089fd977ea153d692)

**new alerts:**

* 6 for Dereferenced variable may be null

**fixed alerts:**

* 1 for Dereferenced variable may be null

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by leerho** [comment]
This pull request **introduces 6 alerts** and **fixes 1** when merging 65da0ff567f5daa6de8d5e1d8be761e4b1d98027 into bd02cc3aa537f7666cbee5ac3d70e0147ead07b2 - [view on LGTM.com](https://lgtm.com/projects/g/DataSketches/sketches-core/rev/pr-cab04539f92dccb7321b8777da9682e29d662538)

**new alerts:**

* 6 for Dereferenced variable may be null

**fixed alerts:**

* 1 for Dereferenced variable may be null

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Pull request merged**
