### PR TITLE
Scalability

### PR DESCRIPTION
**Pull request by Eshcar**
This branch includes all the changes from the refactorConcurrent branch (#232) plus some changes to improve scalability. They can be merged together or separately.
Additional changes for example,
(1) a knob for setting the exact mode limit in concurrent theta sketches,  
(2) moving ConcurrentPropagationService to a separate (singleton) class, to allow controlling number of threads in pool 
(3) in addition it removes cache limit property from theta buffer. Instead the limit is controlled through the parameter K (lgK) of the local sketch.

The API changes in this branch are compatible with the last pull request in characterization repository
#https://github.com/DataSketches/characterization/pull/14

### CODE REVIEW

**Comment by leerho** [comment]
I would like you to make the changes suggested in the other PR and then pull them into this one.  

Then rebase this PR to the latest master, and delete the other PR.  Once I have looked at the combined PR then we can merge into master.

**Comment by Eshcar** [comment]
I will make the changes in the other PR and will merge them into one.
Will be ready early next week.

**Comment by leerho** [comment]
@Eshcar 
Looking forward to your next revision ... :)

**Comment by Eshcar** [comment]
@leerho 
Did you have a chance to take a look at the revision?

**Comment by Eshcar** [comment]
You are right.
I removed `resetShared()`, `sharedHashUpdate()`, `getEstimationSnapshot()`, and `isSharedEstimationMode()` from `ConcurrentShareThetaSketch`.

I hope it can now be merged to master

**Comment by Eshcar** [comment]
Thanks Lee for helping work on this branch :)

**Pull request merged**
